<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\bmslib\bmslib.csproj" />
    <ProjectReference Include="..\bmsmodel\bmsmodel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CIDbConnection.Core">
      <HintPath>..\bmslib\CustomLibDll\CIDbConnection.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
