<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CustomLibDll\NewFolder\**" />
    <EmbeddedResource Remove="CustomLibDll\NewFolder\**" />
    <None Remove="CustomLibDll\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CIDbConnection.Core">
      <HintPath>CustomLibDll\CIDbConnection.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resource\SystemMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SystemMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resource\SystemMessages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SystemMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
